# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:Bạn có yêu Trường khum?
    branches: [ main ]
  pull_request:,có
    branches: [ main ] kó

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: yêu vl

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:yêu 
  # This workflow contains a single job called "build"
  build:không 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest à có

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: nhé
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 tym

      # Runs a single command using the runners shell
      - name: Run a one-line script bạn có yêu mình không 
        run: echo Hello, Cậu?

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: | chọn đi
          echo Add other actions to build,
          echo test, and deploy your project.
